apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pulse-service
  namespace: argocd
  labels:
    app: pulse-service
spec:
  project: default
  source:
    repoURL: https://github.com/apsferreira/pulse-service
    targetRevision: HEAD
    path: deploy/k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: production
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
